// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(WorldBuilderDbContext))]
    [Migration("20230721215652_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldBuilderDAL.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("World");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fadfffad-7837-4893-b1a7-003aa2c88917"),
                            Description = "World 1 Description",
                            Name = "World 1"
                        },
                        new
                        {
                            Id = new Guid("ce8cdf75-2272-4449-9862-3fae32eb732e"),
                            Description = "World 2 Description",
                            Name = "World 2"
                        },
                        new
                        {
                            Id = new Guid("835e8891-29d3-433a-ab61-bdd50926204f"),
                            Description = "World 3 Description",
                            Name = "World 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
